/**
 * 能力テンプレートの実行メタデータ（分類器・検証スクリプト・simulator で共有）。
 */

/** runClassifiedCardAbility の payAbilityCost をスキップし、handler 側でコスト処理する template */
export const TEMPLATE_HANDLES_OWN_COST = [
  "kidou_hand_cost_wait_pick_hand",
  "kidou_hand_discard_activate_wait_opp_bonus",
  "kidou_hand_discard_trigger_ability",
  "kidou_energy_or_activate_member",
  "kidou_energy_deck_pick_live",
  "kidou_wait_to_stage",
  "kidou_stage_wait_pick_hand",
  "live_start_pay_or_hand_discard",
  "live_start_mandatory_energy_deck_unless_hand_discard",
  "optional_energy_live_score_plus",
  "deck_reveal_until_live",
  "kidou_hand_discard_wait_live_score_pay",
  "kidou_hand_reveal_to_under",
  "kidou_heart_color_deck_reveal_pick",
  "kidou_self_wait_hand_enter_energy",
  "kidou_wait_shuffle_deck_bottom_activate",
  "kidou_self_to_wait_opp_wait",
  "toujou_hand_discard_draw_plus",
  "toujou_optional_self_wait_recover",
  "toujou_wait_enter_cost_sum",
  "toujou_optional_all_members_relocate",
  "toujou_optional_wait_to_deck_top",
  "toujou_optional_energy_under",
  "toujou_hand_discard_wait_heart_dual_pick",
  "toujou_bibi_wait_opp_active_wait",
  "live_start_optional_energy_waiting_reorder_deck_top",
  "toujou_main_phase_live_from_waiting",
  "ability_sequence",
  "toujou_multi_wait_draw_per_count",
  "live_start_waiting_deck_bottom_tiered",
  "toujou_self_wait_draw_then_conditional_discard",
  "live_start_mill_loop_blade_grant",
  "live_start_pay_or_discard_conditional_grant_members",
  "live_start_dollcostra_cost_set_grant_if",
  "live_start_hand_discard_cost_boost_grant_if",
  "live_start_hand_named_discard_grant_jouji",
  "live_start_hand_discard_same_unit_grant",
  "live_start_hand_discard_same_group_grant",
  "live_start_hand_discard_optional_blade_per",
  "live_start_hand_discard_series_member_blade_grant",
  "heart_color_pick_grant",
  "live_start_hand_reveal_under_heart_grant",
  "kidou_discard_self_draw_grant",
  "live_start_optional_energy_under_return_grant",
  "live_success_optional_energy_recover_waiting",
  "optional_energy_blade_until_live_end",
];

/** 成功ライブ置き場への移動など executeAbilityBody 外（placement 経路）で処理する template */
export const ABILITY_PLACEMENT_RUNTIME_TEMPLATES = ["jouji_success_live_waiting_substitute"];

/** 相手盤面操作を委譲する simulator ヘルパー（audit-dual-mode-gaps が参照） */
export const OPPONENT_DUAL_DELEGATE_HELPERS = [
  "openSoloOpponentMemberWaitPickDialog",
  "openSoloOpponentMemberWaitPickMultiDialog",
  "openOppWaitPickFromPool",
  "mutateInactiveOpponentBoard",
  "readInactiveOpponentBoard",
  "readFromTargetPlayerBoard",
  "runOnTargetPlayerBoard",
  "runOpponentHandDiscardLoop",
  "runOpponentHandTrimThenDraw",
  "openPickSelfOrOpponentDialog",
  "listOpponentHandForDecision",
  "moveOpponentHandCardToWaiting",
  "openOpponentPlayerChoiceDialog",
  "openOpponentOptionalHandDiscardDialog",
  "soloOpponentStageMemberCandidates",
  "listInactiveOpponentMemberCandidates",
  "runAbilityChoiceTextsSequential",
  "executeAbilityChoiceText",
  "countBothPlayersStageMembers",
  "countOpponentSuccessLiveCards",
  "ownSeriesCostSumHigherThanOpponent",
  "opponentStageMemberCosts",
  "opponentLiveScoreEstimate",
  "ownLiveScoreEstimate",
  "listOpponentStageMembersExcludingName",
  "runPb1018WaitEnterFlow",
  "grantBladesToAllOpponentStageMembers",
  "openOpponentAnswerChoiceDialog",
  "opponentDecisionLeadPrefix",
  "listOpponentHandForDecision",
  "listInactiveOpponentMemberCandidates",
  "setLiveSessionBlockSuccessLivePlacement",
  "rotateStageAreasClockwiseForPlayer",
  "syncJoujiPassiveEffectsAll",
];

/** executeAbilityBody 内で手動ガイド／常時トラックのみ（自動解決の対象外） */
export const TEMPLATES_META_IN_EXECUTE_BODY = ["guided_manual", "passive_track"];

/** 自動効果だが executeAbilityBody ではなく fireJidouAuto 経路で処理 */
export const JIDOU_AUTO_TEMPLATES = [
  "jidou_leave_stage_activate_one",
  "jidou_leave_stage_hand_pick_recover",
  "jidou_leave_stage_deck_look_pick",
  "jidou_leave_stage_draw_discard",
  "jidou_enter_or_baton_draw",
  "jidou_area_move_grant_jouji",
  "jidou_center_member_move_choice",
  "jidou_area_move_draw",
  "jidou_area_move_energy_wait",
  "jidou_area_move_wait_pick_hand",
  "jidou_area_move_opp_wait",
  "jidou_yell_grant_jouji",
  "jidou_yell_grant_jouji_nobh_members",
  "jidou_yell_grant_jouji_no_bh",
  "jidou_yell_grant_heart",
  "jidou_yell_grant_heart_per_live_capped",
  "jidou_yell_draw",
  "jidou_leave_stage_position_change",
  "jidou_stage_entry_draw_until",
  "jidou_on_cost_enter_draw",
  "jidou_on_cost_enter_energy_wait",
  "jidou_area_move_activate_energy",
  "jidou_move_or_energy_draw_grant",
  "jidou_card_to_waiting_pick_hand",
  "jidou_live_zone_to_waiting_deck",
  "jidou_yell_retry_no_live",
  "jidou_yell_retry_low_bh",
  "jidou_yell_discard_nobh_series_extra_yell",
  "jidou_yell_discard_nobh_series_multi_extra_yell",
  "jidou_waiting_to_hand_place_named_live",
  "jidou_live_placed_grant_stage_member",
  "jidou_center_muse_ability_position_change",
  "jidou_center_muse_ability_score_if_moved",
  "jidou_opp_wait_draw",
  "jidou_series_enter_pay_energy",
  "jidou_hand_to_waiting_grant",
  "jidou_series_enter_grant",
  "jidou_series_enter_opp_wait",
  "jidou_self_active_to_wait_draw_discard",
  "jidou_energy_placed_grant",
  "jidou_baton_leave_activate_energy",
  "jidou_leave_stage_hand_grant_member",
  "jidou_member_live_start_grant_all_heart",
  "jidou_member_live_success_draw",
  "jidou_live_success_or_area_move_wait_under",
  "jidou_yell_optional_hand_live_extra_yell",
  "jidou_series_member_to_center_blade_grant",
];

/** @param {string} template */
export function templateHandlesOwnCost(template) {
  return TEMPLATE_HANDLES_OWN_COST.indexOf(template) >= 0;
}
